# Generated by Django 5.1.7 on 2025-04-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
