# Generated by Django 5.1.5 on 2025-03-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='Subscribe',
        ),
    ]
