# Generated by Django 5.1.5 on 2025-02-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productreview_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='rating'),
        ),
    ]
