# Generated by Django 5.1.5 on 2025-04-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcolor_product_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name_plural': 'Product Colors'},
        ),
    ]
