# Generated by Django 5.1.5 on 2025-04-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.productsize'),
            preserve_default=False,
        ),
    ]
