# Generated by Django 5.1.5 on 2025-04-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='tag',
        ),
    ]
