# Generated by Django 5.1.5 on 2025-04-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_basket_basket_item_basketitem_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ('-created_date',)},
        ),
    ]
