# Generated by Django 5.1.5 on 2025-04-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
