# Generated by Django 5.1.5 on 2025-04-15 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_wishlistitem_wishlist'),
        ('product', '0005_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='is_active',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='product.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
