# Generated by Django 5.1.7 on 2025-04-17 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_basket_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.basket'),
            preserve_default=False,
        ),
    ]
