# Generated by Django 5.1.5 on 2025-04-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_user_alter_order_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
