# Generated by Django 5.1.5 on 2025-04-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
